import React from "react";

function StepFourReport({ reportMarkup }) {
  const handlePrint = () => {
    const printWindow = window.open("", "_blank", "width=900,height=700");
    printWindow.document.write(`
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <title>Carbon Footprint Report</title>
        <style>
          @page {
            size: A4;
            margin: 20mm 15mm;
          }

          * { box-sizing: border-box; margin: 0; padding: 0; }

          body {
            font-family: 'Segoe UI', Arial, sans-serif;
            font-size: 11pt;
            color: #1a2318;
            background: #fff;
            padding: 0;
          }

          .report-header {
            text-align: center;
            padding-bottom: 14px;
            margin-bottom: 20px;
            border-bottom: 2px solid #2d6a4f;
          }

          .report-header h1 {
            font-size: 18pt;
            color: #2d6a4f;
            margin-bottom: 4px;
          }

          .report-header p {
            font-size: 9pt;
            color: #6b7c69;
          }

          .report-section {
            border: 1px solid #dde9e2;
            border-radius: 6px;
            padding: 10px 13px;
            margin-bottom: 12px;
            background: #ffffff;
            border-left: 3px solid #74c69d;
            page-break-inside: avoid;
          }

          h3 {
            font-size: 11pt;
            font-weight: 700;
            color: #2d6a4f;
            margin-bottom: 8px;
          }

          h4 {
            font-size: 9.5pt;
            font-weight: 600;
            color: #6b7c69;
            margin: 10px 0 5px;
            text-transform: uppercase;
            letter-spacing: 0.05em;
          }

          ul {
            padding-left: 16px;
            margin: 0 0 8px;
            font-size: 10pt;
            line-height: 1.8;
          }

          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 6px;
            font-size: 9.5pt;
          }

          th {
            background: #e8f5ee;
            color: #2d6a4f;
            padding: 6px 8px;
            text-align: left;
            font-weight: 600;
            font-size: 9pt;
          }

          td {
            padding: 5px 8px;
            border-bottom: 1px solid #dde5db;
            color: #1a2318;
          }

          tr:last-child td { border-bottom: none; }
          tr:nth-child(even) td { background: #f7faf7; }

          .report-table {
            width: 100%;
            border-collapse: collapse;
          }

          .report-footer {
            margin-top: 24px;
            padding-top: 10px;
            border-top: 1px solid #dde5db;
            font-size: 8.5pt;
            color: #6b7c69;
            text-align: center;
          }
        </style>
      </head>
      <body>
        <div class="report-header">
          <h1>Sri Lanka Carbon Footprint Report</h1>
          <p>Generated on ${new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" })} &nbsp;|&nbsp; Travel Agent Carbon Intake System</p>
        </div>
        ${reportMarkup}
        <div class="report-footer">
          This report was generated by the Sri Lanka Tourist Carbon Footprint Calculator.
          Transport emissions are calculated separately and not included in this report.
        </div>
      </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
      printWindow.close();
    }, 500);
  };

  return (
    <section className="step active">
      <h2>Final Report</h2>
      <p className="muted">Review the complete trip carbon footprint report below. Use the button to download as PDF.</p>
      <div className="report" dangerouslySetInnerHTML={{ __html: reportMarkup }} />
      <div className="actions">
        <button className="btn btn-primary" type="button" onClick={handlePrint}>
          Download / Print as PDF (A4)
        </button>
      </div>
    </section>
  );
}

export default StepFourReport;